### ISSUE TITLE
Quick Start Feedback

### ISSUE THREAD

**Issue by dralabeing** [armleo/OpenLane#5]
This pertains to the doc here:
https://armleo-openlane.readthedocs.io/en/latest/docs/source/quickstart.html:
General Feedback- Adhere to writing style and guidelines.
Suggested sections:
Overview
The overview needs rework to make it clean and crisp. See suggested changes below:
OpenLane is an automated RTL to GDSII flow that uses other open sourced tools including OpenROAD, Yosys, Magic, Netgen, CVC, SPEF-Extractor, CU-GR, Klayout. It also provides a number of custom scripts for design exploration, optimization and ECO. The flow performs a complete RTL-GDSII implementation using the skywater 130nm PDK.

The tool encapsulates the underlying tools to allow engineers to configure them all in one place: config.tcl. This file contains assignments to the variables that flow uses.-> Remove this - it's not just engineers who use this tool there are other user profiles. No need to refer to low level details like configuration here.

The quick start guide enables you to get started and run your design flow using OpenLane. It assumes a clean and valid installation of OpenLane. Refer to [OpenLane installation](https://armleo-openlane.readthedocs.io/en/latest/docs/source/installation.html) has been complete.

Using OpenLane (Not Entering The ...)
Why is the make mount being used here if this is described in Installation? This should point to the installation section to check and validate the install.
Don't use Notes that say you are on your own. This is already a warning in Installation- there is no need to add a note here if there is a link to the appropriate link in installation. Simply state what users should do, not what they shouldn't.
Also include commands here to cd to the write directory to execute commands like make mount. Point users to the specific version of OpenLane to use. Otherwise, refer to Updating OpenLane in case they would like to use the latest stable version.

Creating new designs
This section should also apply for existing designs in the OL directory- why only new designs? Make two sub-headings to refer to current designs and another to add new designs,
First show users to run any of the current designs in the repo with the directory structure upfront. Also why is the redundant warning about dockerless install and make mount being repeated here? Don't introduce unnecessary redundancy, warnings, notes etc. 

Add convenient sub-headings like flow.tcl, config.tcl to describe the functions and usage of these files instead of writing long paragraphs to describe their use.

[Running the flow](https://armleo-openlane.readthedocs.io/en/latest/docs/source/quickstart.html#running-the-flow)
Example of incorrect writing: In order to run the flow you need to execute following commands -> should be
To run the flow for <design_name>, Type: 
<cmd>
No need to again explain what this is doing (redundant)

This statement: Now that you know how to run the flow for your design, let’s actually take a deep dive into real life example. is followed by nothing.  What is the point here? Writing Style: Don't use long sentences, real life example and let's etc. Here simply state something like:
Proceed to <link> to learn more about running the RTL-GDSII flow using <design>.

These sections below should not be part of Quick Start but Installation. The assumption is that the user has already completed and knows all details and nuances (docker etc) by the time he/she refers to the Quick Start.
[Advanced: Using custom PDK locations and Docker images](https://armleo-openlane.readthedocs.io/en/latest/docs/source/quickstart.html#advanced-using-custom-pdk-locations-and-docker-images)
[Advanced: Installing other Standard Cell Libraries](https://armleo-openlane.readthedocs.io/en/latest/docs/source/quickstart.html#advanced-installing-other-standard-cell-libraries)

Also, what happens if the user runs into a problem with OpenLane when running the flow? Point them to a Debugging Problems with the flow section.

**Comment by armleo** [comment]
> The overview needs rework to make it clean and crisp. See suggested changes below:
OpenLane is an automated RTL to GDSII flow that uses other open sourced tools including OpenROAD, Yosys, Magic, Netgen, CVC, SPEF-Extractor, CU-GR, Klayout. It also provides a number of custom scripts for design exploration, optimization and ECO. The flow performs a complete RTL-GDSII implementation using the skywater 130nm PDK.

Updated.

> The tool encapsulates the underlying tools to allow engineers to configure them all in one place: config.tcl. This file contains assignments to the variables that flow uses.-> Remove this - it's not just engineers who use this tool there are other user profiles.

Done.

> Why is the make mount being used here if this is described in Installation? This should point to the installation section to check and validate the install.

How else can user enter the Docker container?

> Don't use Notes that say you are on your own. This is already a warning in Installation- there is no need to add a note here if there is a link to the appropriate link in installation. Simply state what users should do, not what they shouldn't.

One warning is never enough. People in Slack build everything from scratch, because they do not like the OSs listed in installation. Then they encounter problems because of their own mistakes and are getting discouraged to use OpenLane. I want to include this warning in every place where users enter Docker containers to remind them to NOT use local installations.

> Point users to the specific version of OpenLane to use. Otherwise, refer to Updating OpenLane in case they would like to use the latest stable version.

Why though?

> Also include commands here to cd to the write directory to execute commands like make mount

let's make a simple rule: The first command of the page should have `cd` in it to specify where you are running and all following commands assume the continuation of the session and don't need the cd command.

> This statement: Now that you know how to run the flow for your design, let’s actually take a deep dive into real life example. is followed by nothing. What is the point here? Writing Style: Don't use long sentences, real life example and let's etc. Here simply state something like:
Proceed to to learn more about running the RTL-GDSII flow using .

Yeah, it was a link to full guide. I removed the link but forgot to remove the sentence.

> These sections below should not be part of Quick Start but Installation.

True, the only reason they are there is because we will merge it to full guide later on. Lets keep it the way it is currently.

> Also, what happens if the user runs into a problem with OpenLane when running the flow? Point them to a Debugging Problems with the flow section.

1. Part of the full guide. 2. I am not aware of any scenarios that people had issues with actually running the flow, that need to be in quickstart instead of full guide.
2. 
Link to the new version: https://armleo-openlane.readthedocs.io/en/merge-window-2/docs/source/contributing_to_docs.html

**Comment by armleo** [comment]
Overview

[TODO] Fix the overview, explain what users will get out of quickstart.
[TODO] config.json
Starting OpenLane
Running the flow
[Make sure it's clear that, it's all they need to run the OpenLane]
Debugging the flow [LINK to troubleshooting]
Adding designs to OpenLane
Advanced: Using custom PDK locations and Docker images
Advanced: Installing other Standard Cell Libraries
